//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input/Characters.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Characters: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Characters()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Characters"",
    ""maps"": [
        {
            ""name"": ""Basic Actions"",
            ""id"": ""2394509e-660c-4e7c-bcc6-9a95d322c5ba"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""cb9f8223-80ba-4c5d-8df1-2e0c737f0b2e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""0193cdfc-711d-4cfa-af94-8f1ff4f5af80"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialMove"",
                    ""type"": ""Button"",
                    ""id"": ""5168ea14-6af9-4634-9362-c363608db036"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""9eccb1f2-2382-44fe-ad40-f8dac943f733"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Instrument1"",
                    ""type"": ""Button"",
                    ""id"": ""9584c007-2c63-4fe0-a759-6cd624bd8d68"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Instrument2"",
                    ""type"": ""Button"",
                    ""id"": ""4dfae9d9-6271-4305-b15f-648b5c05a4e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Instrument3"",
                    ""type"": ""Button"",
                    ""id"": ""5b190013-1b98-4ce9-900b-9cea95476e06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Instrument4"",
                    ""type"": ""Button"",
                    ""id"": ""607e1b44-cead-4fda-8f4a-1f2e9ea4a3f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""6382014e-a95f-43aa-af8f-ad07ad91ec40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f3cd5967-1ae9-446a-bf8d-d2542ee5aa7e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Movement"",
                    ""id"": ""fe9c1dcf-766c-4780-8780-69f324ce51b7"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a5aad2fc-558e-45af-8a8f-c06402068c33"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1f3a41ef-ae1e-48c7-b76f-6c230d9704f2"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b31860b3-d340-452f-837a-e1ae42112653"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""48498b1b-c7de-49a5-a469-90b644d87bfa"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""552c8791-846a-43c0-bd28-a2452e238b97"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5602f352-a68e-4f36-ac94-dffa83f448de"",
                    ""path"": ""<Keyboard>/#(E)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6f0e26a-8741-4b00-a125-d127cc71e234"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce5e9709-3cb1-47b7-b747-f6a20735422f"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""573f26a3-4062-4171-98ea-60f439c14f9a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0)"",
                    ""groups"": """",
                    ""action"": ""Instrument1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""683d0eb6-6e53-443b-aa01-d614bb8b8c3f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0040d051-de7e-40b1-b320-879089148c50"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ce5e8ec-4426-41ee-b88b-ec029e2c2a99"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": ""Scale"",
                    ""groups"": """",
                    ""action"": ""Instrument2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""798807b6-f3ad-4139-bfa6-7646be929df3"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=2)"",
                    ""groups"": """",
                    ""action"": ""Instrument3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dce1462c-71ff-4fba-9740-d4363ed84dde"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=3)"",
                    ""groups"": """",
                    ""action"": ""Instrument4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8178c8a8-7d01-48c9-ae24-7e1c729d0a03"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65226c10-a54d-411b-b8dd-09b2ba1712cf"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu Diving"",
            ""id"": ""1b54912d-9f0d-4dc4-90b9-0f28ecfc06d9"",
            ""actions"": [
                {
                    ""name"": ""VerticalScroll"",
                    ""type"": ""Value"",
                    ""id"": ""3869b3a9-5494-4303-b6a2-1ee6aae40f94"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HorizontalScroll"",
                    ""type"": ""Value"",
                    ""id"": ""be58be2a-20f4-4282-bdeb-e1d210f3d701"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Accept"",
                    ""type"": ""Button"",
                    ""id"": ""48c73492-9bde-46e0-b8ba-9334d5f14b1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""f6299693-ff20-44f7-83b3-41722e9803d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""7e122116-ec35-48c2-8246-1533473d124e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""KeyboardWS"",
                    ""id"": ""02e528ef-99ad-48c1-bf38-5d9c07fbb377"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e2c9355f-ec1d-4e8b-847e-a857e2a8032f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d062eb26-b392-45b8-99e1-bdabed82a608"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""KeyboardUpDown"",
                    ""id"": ""18f9bea2-2a41-4bca-bc73-a9bc681b82eb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6158f2c7-3e83-4881-b4a0-e173e3aa62ec"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a657d83f-7e58-49d9-ac2a-c3a7fb87f666"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""98292163-ef55-4a6a-9597-d5e9d0e49bc6"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4ca43b7-c241-4615-bb24-d53e28bd9622"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21b97ecb-6ea6-48c6-9b94-357f953bd886"",
                    ""path"": ""<Gamepad>/dpad/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""KeyboardAD"",
                    ""id"": ""288a01f7-9902-4896-9e55-1a97b1162a82"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""KeyboardLeftRight"",
                    ""id"": ""549886b3-5992-4c20-9d48-842d74474f8e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""89cfc6a4-d47e-43e6-b1eb-bc459171a549"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""660a8d35-39c4-40b2-b7e9-d661edb8477e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ed835e93-1e0b-45ff-a74e-430fade41ab4"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8f905f72-351f-487e-b8fc-a5d8d0c392bb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""faa74d91-3ffb-463d-969d-e38219d615d6"",
                    ""path"": ""<Gamepad>/dpad/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2085a51-4bfd-44c7-ace2-974820852c14"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d7e9ba8-8b26-4b3d-9a97-a9e50da018a0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cb9448b-f84a-4201-b08f-14c53b138d10"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab20fdaf-bb06-4947-bcc1-b3dbbedc5475"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab221597-98a4-400c-9cbc-30f5d22f1882"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08ddd5b3-120c-456f-9561-f32fea7192f7"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56aea275-7182-48f4-b57e-460e3427d7a5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92b4345d-c18c-4d05-b7df-a8cba6bc835a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcc0f76d-f791-456f-87eb-172b6e184df5"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Basic Actions
        m_BasicActions = asset.FindActionMap("Basic Actions", throwIfNotFound: true);
        m_BasicActions_Movement = m_BasicActions.FindAction("Movement", throwIfNotFound: true);
        m_BasicActions_Interact = m_BasicActions.FindAction("Interact", throwIfNotFound: true);
        m_BasicActions_SpecialMove = m_BasicActions.FindAction("SpecialMove", throwIfNotFound: true);
        m_BasicActions_Menu = m_BasicActions.FindAction("Menu", throwIfNotFound: true);
        m_BasicActions_Instrument1 = m_BasicActions.FindAction("Instrument1", throwIfNotFound: true);
        m_BasicActions_Instrument2 = m_BasicActions.FindAction("Instrument2", throwIfNotFound: true);
        m_BasicActions_Instrument3 = m_BasicActions.FindAction("Instrument3", throwIfNotFound: true);
        m_BasicActions_Instrument4 = m_BasicActions.FindAction("Instrument4", throwIfNotFound: true);
        // Menu Diving
        m_MenuDiving = asset.FindActionMap("Menu Diving", throwIfNotFound: true);
        m_MenuDiving_VerticalScroll = m_MenuDiving.FindAction("VerticalScroll", throwIfNotFound: true);
        m_MenuDiving_HorizontalScroll = m_MenuDiving.FindAction("HorizontalScroll", throwIfNotFound: true);
        m_MenuDiving_Accept = m_MenuDiving.FindAction("Accept", throwIfNotFound: true);
        m_MenuDiving_Back = m_MenuDiving.FindAction("Back", throwIfNotFound: true);
        m_MenuDiving_CloseMenu = m_MenuDiving.FindAction("CloseMenu", throwIfNotFound: true);
        m_BasicActions_Attack = m_BasicActions.FindAction("Attack", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Basic Actions
    private readonly InputActionMap m_BasicActions;
    private List<IBasicActionsActions> m_BasicActionsActionsCallbackInterfaces = new List<IBasicActionsActions>();
    private readonly InputAction m_BasicActions_Movement;
    private readonly InputAction m_BasicActions_Interact;
    private readonly InputAction m_BasicActions_SpecialMove;
    private readonly InputAction m_BasicActions_Menu;
    private readonly InputAction m_BasicActions_Instrument1;
    private readonly InputAction m_BasicActions_Instrument2;
    private readonly InputAction m_BasicActions_Instrument3;
    private readonly InputAction m_BasicActions_Instrument4;
    private readonly InputAction m_BasicActions_Attack;
    public struct BasicActionsActions
    {
        private @Characters m_Wrapper;
        public BasicActionsActions(@Characters wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_BasicActions_Movement;
        public InputAction @Interact => m_Wrapper.m_BasicActions_Interact;
        public InputAction @SpecialMove => m_Wrapper.m_BasicActions_SpecialMove;
        public InputAction @Menu => m_Wrapper.m_BasicActions_Menu;
        public InputAction @Instrument1 => m_Wrapper.m_BasicActions_Instrument1;
        public InputAction @Instrument2 => m_Wrapper.m_BasicActions_Instrument2;
        public InputAction @Instrument3 => m_Wrapper.m_BasicActions_Instrument3;
        public InputAction @Instrument4 => m_Wrapper.m_BasicActions_Instrument4;
        public InputAction @Attack => m_Wrapper.m_BasicActions_Attack;
        public InputActionMap Get() { return m_Wrapper.m_BasicActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BasicActionsActions set) { return set.Get(); }
        public void AddCallbacks(IBasicActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_BasicActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BasicActionsActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @SpecialMove.started += instance.OnSpecialMove;
            @SpecialMove.performed += instance.OnSpecialMove;
            @SpecialMove.canceled += instance.OnSpecialMove;
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
            @Instrument1.started += instance.OnInstrument1;
            @Instrument1.performed += instance.OnInstrument1;
            @Instrument1.canceled += instance.OnInstrument1;
            @Instrument2.started += instance.OnInstrument2;
            @Instrument2.performed += instance.OnInstrument2;
            @Instrument2.canceled += instance.OnInstrument2;
            @Instrument3.started += instance.OnInstrument3;
            @Instrument3.performed += instance.OnInstrument3;
            @Instrument3.canceled += instance.OnInstrument3;
            @Instrument4.started += instance.OnInstrument4;
            @Instrument4.performed += instance.OnInstrument4;
            @Instrument4.canceled += instance.OnInstrument4;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
        }

        private void UnregisterCallbacks(IBasicActionsActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @SpecialMove.started -= instance.OnSpecialMove;
            @SpecialMove.performed -= instance.OnSpecialMove;
            @SpecialMove.canceled -= instance.OnSpecialMove;
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
            @Instrument1.started -= instance.OnInstrument1;
            @Instrument1.performed -= instance.OnInstrument1;
            @Instrument1.canceled -= instance.OnInstrument1;
            @Instrument2.started -= instance.OnInstrument2;
            @Instrument2.performed -= instance.OnInstrument2;
            @Instrument2.canceled -= instance.OnInstrument2;
            @Instrument3.started -= instance.OnInstrument3;
            @Instrument3.performed -= instance.OnInstrument3;
            @Instrument3.canceled -= instance.OnInstrument3;
            @Instrument4.started -= instance.OnInstrument4;
            @Instrument4.performed -= instance.OnInstrument4;
            @Instrument4.canceled -= instance.OnInstrument4;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
        }

        public void RemoveCallbacks(IBasicActionsActions instance)
        {
            if (m_Wrapper.m_BasicActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBasicActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_BasicActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BasicActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BasicActionsActions @BasicActions => new BasicActionsActions(this);

    // Menu Diving
    private readonly InputActionMap m_MenuDiving;
    private List<IMenuDivingActions> m_MenuDivingActionsCallbackInterfaces = new List<IMenuDivingActions>();
    private readonly InputAction m_MenuDiving_VerticalScroll;
    private readonly InputAction m_MenuDiving_HorizontalScroll;
    private readonly InputAction m_MenuDiving_Accept;
    private readonly InputAction m_MenuDiving_Back;
    private readonly InputAction m_MenuDiving_CloseMenu;
    public struct MenuDivingActions
    {
        private @Characters m_Wrapper;
        public MenuDivingActions(@Characters wrapper) { m_Wrapper = wrapper; }
        public InputAction @VerticalScroll => m_Wrapper.m_MenuDiving_VerticalScroll;
        public InputAction @HorizontalScroll => m_Wrapper.m_MenuDiving_HorizontalScroll;
        public InputAction @Accept => m_Wrapper.m_MenuDiving_Accept;
        public InputAction @Back => m_Wrapper.m_MenuDiving_Back;
        public InputAction @CloseMenu => m_Wrapper.m_MenuDiving_CloseMenu;
        public InputActionMap Get() { return m_Wrapper.m_MenuDiving; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuDivingActions set) { return set.Get(); }
        public void AddCallbacks(IMenuDivingActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuDivingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuDivingActionsCallbackInterfaces.Add(instance);
            @VerticalScroll.started += instance.OnVerticalScroll;
            @VerticalScroll.performed += instance.OnVerticalScroll;
            @VerticalScroll.canceled += instance.OnVerticalScroll;
            @HorizontalScroll.started += instance.OnHorizontalScroll;
            @HorizontalScroll.performed += instance.OnHorizontalScroll;
            @HorizontalScroll.canceled += instance.OnHorizontalScroll;
            @Accept.started += instance.OnAccept;
            @Accept.performed += instance.OnAccept;
            @Accept.canceled += instance.OnAccept;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
            @CloseMenu.started += instance.OnCloseMenu;
            @CloseMenu.performed += instance.OnCloseMenu;
            @CloseMenu.canceled += instance.OnCloseMenu;
        }

        private void UnregisterCallbacks(IMenuDivingActions instance)
        {
            @VerticalScroll.started -= instance.OnVerticalScroll;
            @VerticalScroll.performed -= instance.OnVerticalScroll;
            @VerticalScroll.canceled -= instance.OnVerticalScroll;
            @HorizontalScroll.started -= instance.OnHorizontalScroll;
            @HorizontalScroll.performed -= instance.OnHorizontalScroll;
            @HorizontalScroll.canceled -= instance.OnHorizontalScroll;
            @Accept.started -= instance.OnAccept;
            @Accept.performed -= instance.OnAccept;
            @Accept.canceled -= instance.OnAccept;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
            @CloseMenu.started -= instance.OnCloseMenu;
            @CloseMenu.performed -= instance.OnCloseMenu;
            @CloseMenu.canceled -= instance.OnCloseMenu;
        }

        public void RemoveCallbacks(IMenuDivingActions instance)
        {
            if (m_Wrapper.m_MenuDivingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuDivingActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuDivingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuDivingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuDivingActions @MenuDiving => new MenuDivingActions(this);
    public interface IBasicActionsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnSpecialMove(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnInstrument1(InputAction.CallbackContext context);
        void OnInstrument2(InputAction.CallbackContext context);
        void OnInstrument3(InputAction.CallbackContext context);
        void OnInstrument4(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
    }
    public interface IMenuDivingActions
    {
        void OnVerticalScroll(InputAction.CallbackContext context);
        void OnHorizontalScroll(InputAction.CallbackContext context);
        void OnAccept(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnCloseMenu(InputAction.CallbackContext context);
    }
}
